# Generated by Django 5.2.7 on 2025-11-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='image')),
                ('document', models.FileField(upload_to='file')),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
