# Generated by Django 5.2.7 on 2025-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vedio',
            field=models.FileField(default='', upload_to='vedio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
