# Generated by Django 5.2.7 on 2025-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_files/')),
            ],
        ),
    ]
