# Generated by Django 5.2.7 on 2025-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
