# Generated by Django 5.2.7 on 2025-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmpassword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
