# Generated by Django 5.2.7 on 2025-11-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
